#!/bin/bash
set -euo pipefail

# configure_rstudio_pki.sh
# Automates updating infra-rstudio/.env with PKI details (CA_URL, FINGERPRINT)
# by reading the config file generated by 'scripts/infra-pki/generate_token.sh'.
#
# Usage: configure_rstudio_pki.sh <path_to_join_pki.env>
# Example: configure_rstudio_pki.sh /tmp/infra-rstudio_join_pki.env
#
# Mirrors: scripts/infra-iam/configure_iam_pki.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RSTUDIO_DIR="$(cd "${SCRIPT_DIR}/../../infra-rstudio" && pwd)"
ENV_FILE="${RSTUDIO_DIR}/.env"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
NC='\033[0m'

# =====================================================================
# CLEANUP TRAP
# =====================================================================

cleanup() {
    local exit_code=$?
    if [ "${exit_code}" -ne 0 ]; then
        echo -e "${RED}[ERROR] configure_rstudio_pki.sh exited with code ${exit_code}${NC}"
    fi
}
trap cleanup EXIT ERR

# =====================================================================
# FUNCTIONS
# =====================================================================

header() {
    echo -e "${BLUE}=== Infra-RStudio PKI Configurator ===${NC}"
    echo "Updating ${ENV_FILE}"
    echo ""
}

assert_deps() {
    local missing=0
    for cmd in grep sed openssl; do
        if ! command -v "${cmd}" &>/dev/null; then
            echo -e "${RED}[ERROR] Required binary '${cmd}' not found in PATH.${NC}"
            missing=1
        fi
    done
    [ "${missing}" -eq 0 ] || return 1
}

update_env() {
    local key="$1"
    local value="$2"
    if [ -z "${value}" ]; then return; fi

    # Escape | in value to not break sed delimiter
    local escaped_value
    escaped_value=$(printf '%s' "${value}" | sed 's/|/\\|/g')

    if grep -q "^${key}=" "${ENV_FILE}"; then
        # Use | as sed delimiter to safely handle URLs
        sed -i "s|^${key}=.*|${key}=${escaped_value}|" "${ENV_FILE}"
    else
        echo "${key}=${value}" >> "${ENV_FILE}"
    fi
    echo -e "  Updated ${key}: ${GREEN}${value}${NC}"
}

verify_ca_reachable() {
    local ca_url="$1"
    echo ""
    echo -e "${BLUE}Verifying CA reachability...${NC}"
    if command -v openssl &>/dev/null; then
        # Extract host and port from URL (e.g. https://pki.example.com:9000)
        local host
        host=$(echo "${ca_url}" | sed -E 's|https?://([^/:]+).*|\1|')
        local port
        port=$(echo "${ca_url}" | sed -E 's|.*:([0-9]+).*|\1|')
        port="${port:-443}"

        if echo "" | openssl s_client -connect "${host}:${port}" \
            -brief 2>/dev/null | grep -q "CONNECTED"; then
            echo -e "  ${GREEN}CA is reachable at ${host}:${port}${NC}"
        else
            echo -e "  ${YELLOW}Warning: Could not connect to ${host}:${port}${NC}"
            echo -e "  ${YELLOW}This may be expected if PKI is on a different network segment.${NC}"
            echo -e "  ${YELLOW}CA_URL and FINGERPRINT have been written to .env regardless.${NC}"
        fi
    fi
}

# =====================================================================
# MAIN
# =====================================================================

header

# Validate inputs
if [ "$#" -ne 1 ]; then
    echo -e "${RED}Error: Expected exactly one argument.${NC}"
    echo ""
    echo "Usage:   $0 <path_to_join_pki.env>"
    echo "Example: $0 /tmp/infra-rstudio_join_pki.env"
    echo ""
    echo "The input file should contain lines in the format:"
    echo "  CA_URL=\"https://pki.example.com:9000\""
    echo "  FINGERPRINT=\"<sha256-hex-string>\""
    exit 1
fi

INPUT_FILE="$1"

# Assert runtime dependencies
assert_deps

# Assert .env exists
if [ ! -f "${ENV_FILE}" ]; then
    echo -e "${RED}Error: infra-rstudio/.env not found at ${ENV_FILE}.${NC}"
    echo "Copy .env.example to .env before running this script."
    exit 1
fi

if [ ! -f "${INPUT_FILE}" ]; then
    echo -e "${RED}Error: Input file '${INPUT_FILE}' not found.${NC}"
    exit 1
fi

echo -e "Reading config from: ${BLUE}${INPUT_FILE}${NC}"
echo "------------------------------------------------"

# Parse variables safely — grep-based parsing, no unsafe sourcing
CA_URL=$(grep '^CA_URL=' "${INPUT_FILE}" | cut -d= -f2- | tr -d '"' || true)
FINGERPRINT=$(grep '^FINGERPRINT=' "${INPUT_FILE}" | cut -d= -f2- | tr -d '"' || true)

if [ -z "${CA_URL}" ] && [ -z "${FINGERPRINT}" ]; then
    echo -e "${RED}Error: Could not find CA_URL or FINGERPRINT in input file.${NC}"
    echo "Expected format:"
    echo "  CA_URL=\"https://pki.example.com:9000\""
    echo "  FINGERPRINT=\"<sha256-hex-string>\""
    exit 1
fi

# Update .env
update_env "CA_URL" "${CA_URL}"
update_env "CA_FINGERPRINT" "${FINGERPRINT}"

# Connectivity check (soft — non-fatal warning only)
if [ -n "${CA_URL}" ]; then
    verify_ca_reachable "${CA_URL}"
fi

echo ""
echo "------------------------------------------------"
echo -e "${GREEN}Success! infra-rstudio/.env updated with PKI configuration.${NC}"
echo ""
echo "Next steps:"
echo "  1. Validate the stack:  scripts/infra-rstudio/validate_rstudio.sh --pre-deploy"
echo "  2. Deploy the stack:    scripts/infra-rstudio/deploy_rstudio.sh"
echo ""
