apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: rstudio-default-deny
  namespace: botanical
spec:
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-portal
  namespace: botanical
spec:
  podSelector:
    matchLabels:
      app: nginx-portal
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: traefik
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-portal-to-backends
  namespace: botanical
spec:
  podSelector:
    matchExpressions:
      - {key: app, operator: In, values: [rstudio, telemetry-api]}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: nginx-portal
    ports:
    - protocol: TCP
      port: 4180
