#!/bin/bash
set -euo pipefail

# configure_iam_pki.sh
# Automates updating infra-iam/.env with PKI details (CA_URL, FINGERPRINT) 
# by reading the config file generated by 'scripts/infra-pki/generate_token.sh'.

WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../infra-iam" && pwd)"
ENV_FILE="$WORKDIR/.env"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

header() {
    clear
    echo -e "${BLUE}=== Infra-IAM PKI Configurator ===${NC}"
    echo "Updating $ENV_FILE"
    echo ""
}

update_env() {
    local key=$1
    local value=$2
    if [ -z "$value" ]; then return; fi
    
    # Escape special chars for sed (urls, etc)
    # This acts as a basic replacement: Key=... -> Key=NewValue
    if grep -q "^$key=" "$ENV_FILE"; then
        # Use simple sed with | delimiter to handle URLs
        sed -i "s|^$key=.*|$key=$value|" "$ENV_FILE"
    else
        echo "$key=$value" >> "$ENV_FILE"
    fi
    echo -e "Updated $key: ${GREEN}$value${NC}"
}

header

if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <path_to_join_pki.env>"
    echo "Example: $0 /tmp/infra-iam_join_pki.env"
    exit 1
fi

INPUT_FILE="$1"

if [ ! -f "$INPUT_FILE" ]; then
    echo -e "${RED}Error: Input file '$INPUT_FILE' not found.${NC}"
    exit 1
fi

echo -e "Reading config from: ${BLUE}$INPUT_FILE${NC}"
echo "------------------------------------------------"

# Parse variables (Basic evaluation safer than sourcing strictly if format is known simple)
# We look for CA_URL="..." and FINGERPRINT="..."
# Using source in a subshell to safely extract vars without polluting current shell
CA_URL=$(grep '^CA_URL=' "$INPUT_FILE" | cut -d= -f2- | tr -d '"' || true)
FINGERPRINT=$(grep '^FINGERPRINT=' "$INPUT_FILE" | cut -d= -f2- | tr -d '"' || true)

if [ -z "$CA_URL" ] && [ -z "$FINGERPRINT" ]; then
    echo -e "${RED}Error: Could not find CA_URL or FINGERPRINT in input file.${NC}"
    exit 1
fi

# Update .env
update_env "CA_URL" "$CA_URL"
update_env "FINGERPRINT" "$FINGERPRINT"

echo "------------------------------------------------"
echo -e "${GREEN}Success! infra-iam/.env updated.${NC}"
echo ""
echo "You can now start/restart infra-iam:"
echo "cd ../infra-iam && docker compose up -d"
echo ""
